language: ruby
rvm:
  - 2.2.3
services:
  - redis-server
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
addons:
  postgresql: "9.5"
